### ISSUE TITLE
export command not working

### ISSUE THREAD

**Issue by gi4nks** [gi4nks/ambros#4]
{2016/12/11 - 12:20:10} |ER| Error... Value must be provided!
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x1de020, 0xc4200140f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/urfave/cli%2ev1.HandleAction.func1(0xc42004b948)
	/Users/gianluca/Projects/go/src/gopkg.in/urfave/cli.v1/app.go:473 +0x29e
panic(0x1de020, 0xc4200140f0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
main.CmdExport.func1()
	/Users/gianluca/Projects/go/src/github.com/gi4nks/ambros/main.go:205 +0x52d
main.commandWrapper(0xc4200ac3c0, 0xc42004b478)
	/Users/gianluca/Projects/go/src/github.com/gi4nks/ambros/main.go:384 +0x19
main.CmdExport(0xc4200ac3c0, 0x0, 0x0)
	/Users/gianluca/Projects/go/src/github.com/gi4nks/ambros/main.go:222 +0x46
reflect.Value.call(0x1d3fa0, 0x22d790, 0x13, 0x21393f, 0x4, 0xc42004b908, 0x1, 0x1, 0xaf1f8, 0x20b3c0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x1d3fa0, 0x22d790, 0x13, 0xc42004b908, 0x1, 0x1, 0x0, 0xc42004b8e8, 0xb2946)
	/usr/local/go/src/reflect/value.go:302 +0xa4
gopkg.in/urfave/cli%2ev1.HandleAction(0x1d3fa0, 0x22d790, 0xc4200ac3c0, 0x0, 0x0)
	/Users/gianluca/Projects/go/src/gopkg.in/urfave/cli.v1/app.go:482 +0x1e0
gopkg.in/urfave/cli%2ev1.Command.Run(0x21404b, 0x6, 0x0, 0x0, 0xc420074fe0, 0x1, 0x1, 0x21ccd0, 0x29, 0x0, ...)
	/Users/gianluca/Projects/go/src/gopkg.in/urfave/cli.v1/command.go:186 +0xc26
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200d2000, 0xc420094060, 0x2, 0x2, 0x0, 0x0)
	/Users/gianluca/Projects/go/src/gopkg.in/urfave/cli.v1/app.go:235 +0x60c
main.main()
	/Users/gianluca/Projects/go/src/github.com/gi4nks/ambros/main.go:194 +0xd91

**Comment by gi4nks** [comment]
done
